/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailIdRouteImport } from './routes/email.$id'

const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIdRoute = EmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/priority': typeof PriorityRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing' | '/login' | '/priority' | '/email/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing' | '/login' | '/priority' | '/email/$id'
  id: '__root__' | '/' | '/landing' | '/login' | '/priority' | '/email/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PriorityRoute: typeof PriorityRoute
  EmailIdRoute: typeof EmailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/$id': {
      id: '/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof EmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PriorityRoute: PriorityRoute,
  EmailIdRoute: EmailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
