/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as PilotStatusRouteImport } from './routes/pilot-status'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiTransparencyRouteImport } from './routes/ai-transparency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailIdRouteImport } from './routes/email.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotStatusRoute = PilotStatusRouteImport.update({
  id: '/pilot-status',
  path: '/pilot-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTransparencyRoute = AiTransparencyRouteImport.update({
  id: '/ai-transparency',
  path: '/ai-transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIdRoute = EmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/app': typeof AppRoute
  '/assistant': typeof AssistantRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/cookies': typeof CookiesRoute
  '/guardian': typeof GuardianRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/pilot-status': typeof PilotStatusRoute
  '/priority': typeof PriorityRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/tts': typeof ApiTtsRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/app': typeof AppRoute
  '/assistant': typeof AssistantRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/cookies': typeof CookiesRoute
  '/guardian': typeof GuardianRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/pilot-status': typeof PilotStatusRoute
  '/priority': typeof PriorityRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/tts': typeof ApiTtsRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/app': typeof AppRoute
  '/assistant': typeof AssistantRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/cookies': typeof CookiesRoute
  '/guardian': typeof GuardianRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/pilot-status': typeof PilotStatusRoute
  '/priority': typeof PriorityRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/api/tts': typeof ApiTtsRoute
  '/email/$id': typeof EmailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-transparency'
    | '/app'
    | '/assistant'
    | '/briefing'
    | '/channels'
    | '/cookies'
    | '/guardian'
    | '/login'
    | '/objectives'
    | '/onboarding'
    | '/permissions'
    | '/pilot-status'
    | '/priority'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/tts'
    | '/email/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-transparency'
    | '/app'
    | '/assistant'
    | '/briefing'
    | '/channels'
    | '/cookies'
    | '/guardian'
    | '/login'
    | '/objectives'
    | '/onboarding'
    | '/permissions'
    | '/pilot-status'
    | '/priority'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/tts'
    | '/email/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-transparency'
    | '/app'
    | '/assistant'
    | '/briefing'
    | '/channels'
    | '/cookies'
    | '/guardian'
    | '/login'
    | '/objectives'
    | '/onboarding'
    | '/permissions'
    | '/pilot-status'
    | '/priority'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/trust'
    | '/api/tts'
    | '/email/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTransparencyRoute: typeof AiTransparencyRoute
  AppRoute: typeof AppRoute
  AssistantRoute: typeof AssistantRoute
  BriefingRoute: typeof BriefingRoute
  ChannelsRoute: typeof ChannelsRoute
  CookiesRoute: typeof CookiesRoute
  GuardianRoute: typeof GuardianRoute
  LoginRoute: typeof LoginRoute
  ObjectivesRoute: typeof ObjectivesRoute
  OnboardingRoute: typeof OnboardingRoute
  PermissionsRoute: typeof PermissionsRoute
  PilotStatusRoute: typeof PilotStatusRoute
  PriorityRoute: typeof PriorityRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ApiTtsRoute: typeof ApiTtsRoute
  EmailIdRoute: typeof EmailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-status': {
      id: '/pilot-status'
      path: '/pilot-status'
      fullPath: '/pilot-status'
      preLoaderRoute: typeof PilotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-transparency': {
      id: '/ai-transparency'
      path: '/ai-transparency'
      fullPath: '/ai-transparency'
      preLoaderRoute: typeof AiTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/$id': {
      id: '/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof EmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTransparencyRoute: AiTransparencyRoute,
  AppRoute: AppRoute,
  AssistantRoute: AssistantRoute,
  BriefingRoute: BriefingRoute,
  ChannelsRoute: ChannelsRoute,
  CookiesRoute: CookiesRoute,
  GuardianRoute: GuardianRoute,
  LoginRoute: LoginRoute,
  ObjectivesRoute: ObjectivesRoute,
  OnboardingRoute: OnboardingRoute,
  PermissionsRoute: PermissionsRoute,
  PilotStatusRoute: PilotStatusRoute,
  PriorityRoute: PriorityRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ApiTtsRoute: ApiTtsRoute,
  EmailIdRoute: EmailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
